table Treinamentos
	lineageTag: 3b054625-e0d7-4918-9850-727b308db965

	column CODCOLIGADA
		dataType: string
		lineageTag: 1ca3c772-1957-4b6d-9fdd-f7f9fa7a4c5f
		summarizeBy: none
		sourceColumn: CODCOLIGADA

		annotation SummarizationSetBy = Automatic

	column CHAPA
		dataType: string
		lineageTag: 119411b1-75d9-40ea-8147-56c1e74608a4
		summarizeBy: none
		sourceColumn: CHAPA

		annotation SummarizationSetBy = Automatic

	column VALOR
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 128b5aa9-8513-4614-90eb-f141deb7d676
		summarizeBy: sum
		sourceColumn: VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"yrl-Latn-BR"}

	column NROVEZES
		dataType: int64
		formatString: 0
		lineageTag: 034298c9-fe63-4f1a-988e-063e0d74237c
		summarizeBy: sum
		sourceColumn: NROVEZES

		annotation SummarizationSetBy = Automatic

	column COLIGADA
		dataType: string
		lineageTag: 7e2ab49c-ff10-49ec-9e95-1652c391baae
		summarizeBy: none
		sourceColumn: COLIGADA

		annotation SummarizationSetBy = Automatic

	column COLABORADOR
		dataType: string
		lineageTag: 0820cb8e-6c24-4c09-8edd-01eae06a3e69
		summarizeBy: none
		sourceColumn: COLABORADOR

		annotation SummarizationSetBy = Automatic

	column CODSECAO
		dataType: string
		lineageTag: f28933c5-a65b-4268-b1d2-3c5be0685338
		summarizeBy: none
		sourceColumn: CODSECAO

		annotation SummarizationSetBy = Automatic

	column SECAO
		dataType: string
		lineageTag: 1227724b-b32c-4b50-a174-b47a541aad14
		summarizeBy: none
		sourceColumn: SECAO

		annotation SummarizationSetBy = Automatic

	column CODFUNCAO
		dataType: string
		lineageTag: 4c34a097-2fe1-4b63-ba8c-3cbe3f045b25
		summarizeBy: none
		sourceColumn: CODFUNCAO

		annotation SummarizationSetBy = Automatic

	column FUNCAO
		dataType: string
		lineageTag: ca3133e3-298c-438f-b07a-6785783ac4ad
		summarizeBy: none
		sourceColumn: FUNCAO

		annotation SummarizationSetBy = Automatic

	column INICIO
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1c0a5f60-183a-4e36-af85-0efe5a0a9653
		summarizeBy: none
		sourceColumn: INICIO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FIM
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4b23576c-e1d7-4b87-851b-f5355000d29a
		summarizeBy: none
		sourceColumn: FIM

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VENCIMENTO = Treinamentos[FIM] + 1
		formatString: Short Date
		lineageTag: e222d57f-a1b8-4e6f-8102-2c263c3e72ac
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column INICIO_FORMATADO = ```
			FORMAT ( 'Treinamentos'[INICIO], "MMM/yyyy", "pt-BR" )
			
			```
		lineageTag: daf32841-f402-43a7-9d87-5a268c833b0e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column FIM_FORMATADO = FORMAT ( 'Treinamentos'[FIM], "MMM/yyyy", "pt-BR" )
		lineageTag: 9c5a7702-7d6a-422e-abee-91a9ad5a63a0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Treinamentos = m
		mode: import
		source =
				let
				    Source = Sql.Database("192.168.42.153", "corpore", [Query="SELECT #(lf)#(tab)PFCODFIX.CODCOLIGADA,#(lf)#(tab)GCOLIGADA.NOMEFANTASIA AS COLIGADA,#(lf)#(tab)PFCODFIX.CHAPA,#(lf)#(tab)PFUNC.NOME AS COLABORADOR,#(lf)#(tab)PFUNC.CODSECAO,#(lf)#(tab)PSECAO.DESCRICAO AS SECAO,#(lf)#(tab)PFUNC.CODFUNCAO,#(lf)#(tab)PFUNCAO.NOME AS FUNCAO,#(lf)#(tab)PFCODFIX.VALOR,#(lf)#(tab)PFCODFIX.NROVEZES,#(lf)#(tab)DATEFROMPARTS(#(lf)#(tab)#(tab)YEAR(PFCODFIX.RECCREATEDON),#(lf)#(tab)#(tab)MONTH(PFCODFIX.RECCREATEDON),#(lf)#(tab)#(tab)1#(lf)#(tab)) AS INICIO,#(lf)#(tab)EOMONTH(DATEADD(MONTH, 2, PFCODFIX.RECCREATEDON)) AS FIM#(lf)#(lf)FROM PFCODFIX #(lf)#(tab)JOIN GCOLIGADA ON (#(lf)#(tab)#(tab)GCOLIGADA.CODCOLIGADA=PFCODFIX.CODCOLIGADA#(lf)#(tab))#(lf)#(tab)JOIN PFUNC ON (#(lf)#(tab)#(tab)PFUNC.CODCOLIGADA=PFCODFIX.CODCOLIGADA AND#(lf)#(tab)#(tab)PFUNC.CHAPA=PFCODFIX.CHAPA#(lf)#(tab))#(lf)#(tab)JOIN PSECAO ON (#(lf)#(tab)#(tab)PSECAO.CODCOLIGADA=PFUNC.CODCOLIGADA AND#(lf)#(tab)#(tab)PSECAO.CODIGO=PFUNC.CODSECAO#(lf)#(tab))#(lf)#(tab)JOIN PFUNCAO ON (#(lf)#(tab)#(tab)PFUNCAO.CODCOLIGADA=PFUNC.CODCOLIGADA AND#(lf)#(tab)#(tab)PFUNCAO.CODIGO=PFUNC.CODFUNCAO#(lf)#(tab))#(lf)#(lf)WHERE 1=1#(lf)#(tab)AND PFCODFIX.CODEVENTO = '9161'#(lf)#(lf)ORDER BY#(lf)#(tab)PFCODFIX.NROVEZES DESC,#(lf)#(tab)PFCODFIX.RECCREATEDON DESC#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"CODCOLIGADA", type text}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Changed Type",{{"COLIGADA", Text.Proper, type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Capitalized Each Word","Sinasc Construcao","Sinasc Construção",Replacer.ReplaceText,{"COLIGADA"}),
				    #"Capitalized Each Word1" = Table.TransformColumns(#"Replaced Value",{{"COLABORADOR", Text.Proper, type text}, {"FUNCAO", Text.Proper, type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Capitalized Each Word1",{{"VALOR", Currency.Type}, {"NROVEZES", Int64.Type}, {"INICIO", type date}, {"FIM", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

