table Medida
	lineageTag: dc2b34c6-4f7d-44b7-9ca9-d5ad5210b499

	measure RNM_EM_DIA = ```
			
			VAR Hoje = TODAY()
			VAR Resultado =
			    CALCULATE(
			        COUNTROWS(RNMs),
			        FILTER(
			            RNMs,
			            NOT ISBLANK(RNMs[VENCRNM]) &&
			            RNMs[VENCRNM] > Hoje + 30
			        )
			    )
			RETURN
			COALESCE(Resultado, 0)
			
			```
		formatString: 0
		lineageTag: 7216bab6-9e87-480b-9bdf-4f08e3834d2e

	measure RNM_A_VENCER = ```
			
			VAR Hoje = TODAY()
			VAR Resultado =
			    CALCULATE(
			        COUNTROWS(RNMs),
			        FILTER(
			            RNMs,
			            NOT ISBLANK(RNMs[VENCRNM]) &&
			            RNMs[VENCRNM] >= Hoje &&
			            RNMs[VENCRNM] <= Hoje + 30
			        )
			    )
			RETURN
			COALESCE(Resultado, 0)
			
			```
		formatString: 0
		lineageTag: e392b919-cda4-446a-afab-96fec6fcb392

	measure RNM_VENCIDOS = ```
			
			VAR Hoje = TODAY()
			VAR Resultado =
			    CALCULATE(
			        COUNTROWS(RNMs),
			        FILTER(
			            RNMs,
			            ISBLANK(RNMs[VENCRNM]) ||
			            RNMs[VENCRNM] < Hoje
			        )
			    )
			RETURN
			COALESCE(Resultado, 0)
			
			```
		formatString: 0
		lineageTag: 2e50b4dc-81cf-4e02-b5bc-acbaa052c650

	measure TOTAL_RNMS = COUNTROWS(RNMs)
		formatString: 0
		lineageTag: d5690b02-7946-46cd-88e1-59decef65047

	partition Medida = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

