SELECT 
	GCOLIGADA.CODCOLIGADA,
	GCOLIGADA.NOMEFANTASIA AS COLIGADA, 
	VOCORRENCIA.NUMEROCAT,
	VNATUREZACAT.NATUREZA,
	PFUNC.CHAPA, 
	PFUNC.NOME,
	PFUNCAO.CODIGO AS CODFUNCAO,
	PFUNCAO.NOME AS FUNCAO,
	PSECAO.CODIGO AS CODSETOR,
	PSECAO.DESCRICAO AS SETOR,
	VOCORRENCIA.CODTIPOOCORRENCIA AS CODTIPOOCORRENCIA,
	VTIPOOCORRENCIA.NOME AS TIPOOCORRENCIA,
	VOCORRENCIA.DATAHORA AS DATAOCORRENCIA,
	VOCORRENCIA.CODSITUACAOGERA AS CODCAUSA,
	VPPRAFONTEGERA.NOME AS CAUSA,
	VOCORRENCIA.DURACAOTRATAMENTO,
	VOCORRENCIA.HOUVEAFASTAMENTO,
	VOCORRENCIA.MORTE

FROM PFUNC
	JOIN GCOLIGADA ON (
		GCOLIGADA.CODCOLIGADA = PFUNC.CODCOLIGADA
	)
	JOIN PFUNCAO ON (
		PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND
		PFUNCAO.CODIGO = PFUNC.CODFUNCAO
	)
	JOIN PSECAO ON (
		PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND
		PSECAO.CODIGO = PFUNC.CODSECAO
	)
	JOIN VOCORRENCIA ON (
		VOCORRENCIA.CODCOLIGADA = PFUNC.CODCOLIGADA AND
		VOCORRENCIA.CHAPA = PFUNC.CHAPA
	)
	JOIN VTIPOOCORRENCIA ON (
		VTIPOOCORRENCIA.CODCOLIGADA = VOCORRENCIA.CODCOLIGADA AND
		VTIPOOCORRENCIA.CODTIPOOCORRENCIA = VOCORRENCIA.CODTIPOOCORRENCIA
	)
	LEFT JOIN VPPRAFONTEGERA ON (
		VPPRAFONTEGERA.CODFONTEGERA = VOCORRENCIA.CODSITUACAOGERA
	)
	LEFT JOIN VOCORRENCIANATUREZAMEDICA ON (
		VOCORRENCIANATUREZAMEDICA.CODCOLIGADA = VOCORRENCIA.CODCOLIGADA AND
		VOCORRENCIANATUREZAMEDICA.CODOCORRENCIA = VOCORRENCIA.CODOCORRENCIA
	)
	LEFT JOIN VNATUREZACAT ON (
		VNATUREZACAT.CODNATUREZA = VOCORRENCIANATUREZAMEDICA.CODNATUREZA
	)
	LEFT JOIN VMEDIDASTOMADAS ON (
		VMEDIDASTOMADAS.CODCOLIGADA = VOCORRENCIA.CODCOLIGADA AND
		VMEDIDASTOMADAS.CODOCORRENCIA = VOCORRENCIA.CODOCORRENCIA
	)