SELECT 
        GCOLIGADA.NOMEFANTASIA AS COLIGADA,
        FCFO.NOMEFANTASIA AS CLIENTE,
        TMOV.DATAEMISSAO,
        TMOV.NUMEROMOV AS NUMERONOTA,
        TMOV.VALORBRUTO,
        TMOV.VALORLIQUIDO,
        TMOV.STATUS AS SITUACAONOTA /* F = Emitida | Q = Recebida | P = Parcialmente Recebida */

FROM TMOV (NOLOCK)
        JOIN GCOLIGADA (NOLOCK) ON (
                GCOLIGADA.CODCOLIGADA=TMOV.CODCOLIGADA
        )
        JOIN FCFO (NOLOCK) ON (
                FCFO.CODCOLIGADA=TMOV.CODCOLIGADA AND 
                FCFO.CODCFO=TMOV.CODCFO
        )

WHERE 1=1
        AND TMOV.STATUS <> 'C' 
        AND (  
                   (TMOV.CODTMV IN ('2.2.04','2.2.05','2.2.07') AND TMOV.CODCOLIGADA = 1) 
                OR (TMOV.CODTMV IN ('2.2.04','2.2.05','2.2.07','2.2.59') AND TMOV.CODCOLIGADA = 5) 
                OR (TMOV.CODTMV IN ('2.2.07','2.2.59') AND TMOV.CODCOLIGADA = 6) 
                OR (TMOV.CODTMV IN ('2.2.05') AND TMOV.CODCOLIGADA = 7)
                OR (TMOV.CODTMV IN ('2.2.00','2.2.24') AND TMOV.CODCOLIGADA = 10)
        )

ORDER BY 
        COLIGADA, 
        CLIENTE