WITH TEMPTABLE AS (
    SELECT 
		ROW_NUMBER() OVER (PARTITION BY PFUNC.CHAPA, PFUNC.CODCOLIGADA ORDER BY PFUFERIAS.FIMPERAQUIS DESC) AS ID,
		PFUNC.CODCOLIGADA AS COLIGADA,
		PFUNC.CHAPA,
		PFUNC.NOME,
		PSECAO.DESCRICAO AS SECAO,
		PCODSITUACAO.DESCRICAO AS SITUACAO,
		CAST(GETDATE() AS DATE) AS HOJE,
		PFUNC.DATAADMISSAO,
		PFUFERIAS.INICIOPERAQUIS,
		PFUFERIAS.FIMPERAQUIS,

		DATEADD(YEAR, 1, PFUFERIAS.FIMPERAQUIS) AS FIMPERCONCESSIVO,

		DATEADD(DAY, 185, PFUFERIAS.FIMPERAQUIS) AS LIMITEGOZO6MESES,

		DATEADD(DAY, 335, PFUFERIAS.FIMPERAQUIS) AS LIMITEGOZO,

		(DATEDIFF(MONTH, INICIOPERAQUIS, CAST(GETDATE() AS DATE)) - IIF(DAY(CAST(GETDATE() AS DATE)) < DAY(INICIOPERAQUIS), 1, 0)) AS AVOSCOMPLETOS,

		(SELECT ISNULL(SUM(PFP.NRODIASFERIAS),0) + ISNULL(SUM(PFP.NRODIASABONO),0) FROM PFUFERIASPER PFP WHERE PFP.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PFP.CHAPA = PFUFERIAS.CHAPA AND PFP.FIMPERAQUIS = PFUFERIAS.FIMPERAQUIS) AS FERIASABONADAS,

		(SELECT ISNULL(SUM(PFP.NRODIASFERIAS),0) + ISNULL(SUM(PFP.NRODIASABONO),0) FROM PFUFERIASPER PFP WHERE PFP.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PFP.CHAPA = PFUFERIAS.CHAPA AND PFP.FIMPERAQUIS = PFUFERIAS.FIMPERAQUIS AND PFP.DATAINICIO > GETDATE()) AS FERIASMARCADAS,

		(SELECT ISNULL(SUM(REF),0) FROM PFMOVCC WHERE CODEVENTO = '0008' AND CODCOLIGADA = PFUNC.CODCOLIGADA AND CHAPA = PFUNC.CHAPA AND ((ANOCOMP = YEAR(PFUFERIAS.INICIOPERAQUIS) AND MESCOMP > MONTH(PFUFERIAS.INICIOPERAQUIS)) OR (ANOCOMP = YEAR(PFUFERIAS.FIMPERAQUIS) AND MESCOMP <= MONTH(PFUFERIAS.FIMPERAQUIS)))) AS FALTAS
		
	FROM PFUNC
		JOIN PCODSITUACAO ON PCODSITUACAO.CODCLIENTE = PFUNC.CODSITUACAO
		JOIN PSECAO ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSECAO.CODIGO = PFUNC.CODSECAO
		JOIN PFUFERIAS ON PFUFERIAS.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFUFERIAS.CHAPA = PFUNC.CHAPA
		FULL JOIN PFUFERIASPER ON PFUFERIASPER.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PFUFERIASPER.CHAPA = PFUFERIAS.CHAPA AND PFUFERIASPER.FIMPERAQUIS = PFUFERIAS.FIMPERAQUIS

	WHERE 
		PFUNC.CODSITUACAO <> 'D'
),

TEMPTABLE2 AS (
	SELECT 
		*,

		CASE 
			WHEN HOJE > FIMPERAQUIS THEN
				(CASE 
					WHEN FALTAS <= 5 THEN 30 
					WHEN FALTAS BETWEEN 6 AND 14 THEN 24 
					WHEN FALTAS BETWEEN 15 AND 23 THEN 18 
					WHEN FALTAS BETWEEN 24 AND 32 THEN 12 
					ELSE 0 
				END) - FERIASABONADAS
			ELSE 
				(CASE 
					WHEN FALTAS <= 5 THEN (AVOSCOMPLETOS * 2.5)
					WHEN FALTAS BETWEEN 6 AND 14 THEN (AVOSCOMPLETOS * 2)
					WHEN FALTAS BETWEEN 15 AND 23 THEN (AVOSCOMPLETOS * 1.5)
					WHEN FALTAS BETWEEN 24 AND 32 THEN AVOSCOMPLETOS
					ELSE 0
				END) - FERIASABONADAS
		END AS SALDOPERIODO

	FROM TEMPTABLE WHERE ID = 1
),

TEMPTABLE3 AS (
	SELECT 
		COLIGADA,
		CHAPA,
		NOME,
		SECAO,
		SITUACAO,
		HOJE,
		DATAADMISSAO,
		INICIOPERAQUIS,
		FIMPERAQUIS,
		FIMPERCONCESSIVO,
		LIMITEGOZO6MESES,
		LIMITEGOZO,
		FERIASABONADAS,
		FERIASMARCADAS,
		FALTAS,
		SALDOPERIODO,

		CASE 
			WHEN FIMPERAQUIS < HOJE AND SALDOPERIODO <= 0 AND FERIASMARCADAS > 0 THEN 'Férias Marcadas'
			WHEN FIMPERAQUIS < HOJE AND SALDOPERIODO <= 0 THEN 'Férias Abonadas'
			WHEN LIMITEGOZO < HOJE AND SALDOPERIODO > 0 THEN 'Férias Vencidas' 
			WHEN FIMPERAQUIS < HOJE AND SALDOPERIODO > 0 THEN 'Férias à Vencer'
			WHEN FIMPERAQUIS >= HOJE THEN 'Férias Parciais'
			ELSE 'Indeterminado'
		END AS STATUS

	FROM TEMPTABLE2
)

SELECT * FROM TEMPTABLE3 ORDER BY NOME
