SELECT 
    GCOLIGADA.NOMEFANTASIA,
    CONVERT(VARCHAR(2), PFPERFF.MESCOMP) + '/' + CONVERT(VARCHAR(4), PFPERFF.ANOCOMP) AS COMPETENCIA,
    PFPERFF.ANOCOMP,
    PFPERFF.MESCOMP,
    PFPERFF.NROPERIODO,
    PFPERFF.BASEFGTS,
    PFPERFF.BASEFGTS13,
    PFPERFF.BASEINSS,
    PFPERFF.BASEINSS13

FROM PFPERFF 
    JOIN GCOLIGADA ON GCOLIGADA.CODCOLIGADA = PFPERFF.CODCOLIGADA

WHERE
    (   
        PFPERFF.BASEFGTS < 0 OR
        PFPERFF.BASEFGTS13  < 0 OR
        PFPERFF.BASEINSS  < 0 OR
        PFPERFF.BASEINSS13  < 0
    )

/*
SELECT
	PFFINANC.CODCOLIGADA,
    CONVERT(VARCHAR(2), MAX(MESCOMP)) + '/' + CONVERT(VARCHAR(4), MAX(ANOCOMP)) AS COMPETENCIA,
    PFFINANC.CODEVENTO,
    PEVENTO.DESCRICAO AS EVENTO,
    SUM(PFFINANC.VALOR) AS VALOR,
    PEVENTO.PROVDESCBASE

FROM PFFINANC
    JOIN PEVENTO ON PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA AND PEVENTO.CODIGO = PFFINANC.CODEVENTO

WHERE 1=1
    AND PFFINANC.CODCOLIGADA = 5
    AND PFFINANC.ANOCOMP = 2025
    AND PFFINANC.MESCOMP = 12
    AND PFFINANC.NROPERIODO IN (3,4)
    AND PEVENTO.PROVDESCBASE IN ('P', 'D')

GROUP BY
    PFFINANC.CODCOLIGADA,
    PFFINANC.ANOCOMP,
    PFFINANC.MESCOMP,
    PFFINANC.CODEVENTO,
    PEVENTO.DESCRICAO,
    PEVENTO.PROVDESCBASE


ORDER BY
    PFFINANC.CODCOLIGADA,
    PEVENTO.PROVDESCBASE DESC,
    PFFINANC.CODEVENTO
*/
