SELECT
	PFFINANC.CODCOLIGADA,
    CONVERT(VARCHAR(2), MAX(MESCOMP)) + '/' + CONVERT(VARCHAR(4), MAX(ANOCOMP)) AS COMPETENCIA,
    PFFINANC.CODEVENTO,
    PEVENTO.DESCRICAO AS EVENTO,
    SUM(PFFINANC.VALOR) AS VALOR,
    PEVENTO.PROVDESCBASE

FROM PFFINANC
    JOIN PEVENTO ON PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA AND PEVENTO.CODIGO = PFFINANC.CODEVENTO

WHERE 1=1
    AND PFFINANC.CODCOLIGADA = 5
    AND PFFINANC.ANOCOMP = 2025
    AND PFFINANC.MESCOMP = 12
    AND PFFINANC.NROPERIODO IN (3,4)
    AND PEVENTO.PROVDESCBASE IN ('P', 'D')

GROUP BY
    PFFINANC.CODCOLIGADA,
    PFFINANC.ANOCOMP,
    PFFINANC.MESCOMP,
    PFFINANC.CODEVENTO,
    PEVENTO.DESCRICAO,
    PEVENTO.PROVDESCBASE


ORDER BY
    PFFINANC.CODCOLIGADA,
    PEVENTO.PROVDESCBASE DESC,
    PFFINANC.CODEVENTO

/*
SELECT 
    MAX(PFPERFF.CODCOLIGADA) AS COLIGADA,
    CONVERT(VARCHAR(2), MAX(PFPERFF.MESCOMP)) + '/' + CONVERT(VARCHAR(4), MAX(PFPERFF.ANOCOMP)) AS COMPETENCIA,
    SUM(PFPERFF.BASEFGTS) AS BASEFGTS,
    SUM(PFPERFF.BASEFGTS13) AS BASEFGTS13,
    SUM(PFPERFF.BASEINSS) AS BASEINSS,
    SUM(PFPERFF.BASEINSS13) AS BASEINSS13,
    SUM(PFPERFF.BASEINSS13OUTRO) AS BASEINSS13OUTRO

FROM PFPERFF 
    
WHERE 1=1
    AND PFPERFF.CODCOLIGADA = 5
    AND PFPERFF.MESCOMP = 12
    AND PFPERFF.ANOCOMP = 2025
    AND PFPERFF.NROPERIODO IN (3,4)
*/
