/*
SELECT
	PFFINANC.CODCOLIGADA,
    PFFINANC.ANOCOMP,
    PFFINANC.MESCOMP,
    PFFINANC.NROPERIODO,
    PFFINANC.CODEVENTO,
    PEVENTO.DESCRICAO,
    SUM(PFFINANC.VALOR) AS VALOR

FROM PFFINANC
    JOIN PEVENTO ON PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA AND PEVENTO.CODIGO = PFFINANC.CODEVENTO

WHERE 1=1
    AND PFFINANC.CODCOLIGADA = 5
    AND PFFINANC.CODEVENTO = '0002'
    AND PFFINANC.ANOCOMP = 2025
    AND PFFINANC.MESCOMP = 10

GROUP BY
    PFFINANC.CODCOLIGADA,
    PFFINANC.ANOCOMP,
    PFFINANC.MESCOMP,
    PFFINANC.NROPERIODO,
    PFFINANC.CODEVENTO,
    PEVENTO.DESCRICAO

ORDER BY
    PFFINANC.CODCOLIGADA,
    PFFINANC.ANOCOMP DESC,
    PFFINANC.MESCOMP DESC,
    PFFINANC.NROPERIODO,
    PFFINANC.CODEVENTO,
    PEVENTO.DESCRICAO
*/

SELECT 
    /*CODCOLIGADA,
    CHAPA,
    BASEFGTS, 
    BASEFGTS13,
    BASEINSS,
    BASEINSS13*/
    SUM(BASEFGTS) AS BASEFGTS, 
    SUM(BASEFGTS13) AS BASEFGTS13,
    SUM(BASEINSS) AS BASEINSS,
    SUM(BASEINSS13) AS BASEINSS13
    
FROM 
    PFPERFF 
    
WHERE 1=1
    AND CODCOLIGADA = 5
    AND MESCOMP = 10
    AND ANOCOMP = 2025