SELECT 
	PFUNC.CODCOLIGADA,
	GCOLIGADA.NOMEFANTASIA,
	PFUNC.CHAPA,
	PFUNC.NOME,
	PCODNACAO.DESCRICAO AS NACIONALIDADE,
	PFUNC.CODSECAO,
	PSECAO.DESCRICAO AS SECAO,
	PFUNC.CODFUNCAO,
	PFUNCAO.NOME AS FUNCAO,
	PPESSOA.DTVENCIDENT AS VENCRNM

FROM PFUNC
	JOIN GCOLIGADA ON (
		GCOLIGADA.CODCOLIGADA=PFUNC.CODCOLIGADA
	)
	JOIN PSECAO ON (
		PSECAO.CODCOLIGADA=PFUNC.CODCOLIGADA AND 
		PSECAO.CODIGO=PFUNC.CODSECAO
	)
	JOIN PFUNCAO ON (
		PFUNCAO.CODCOLIGADA=PFUNC.CODCOLIGADA AND 
		PFUNCAO.CODIGO=PFUNC.CODFUNCAO
	)
	LEFT JOIN PPESSOA ON (
		PPESSOA.CODIGO=PFUNC.CODPESSOA
	)
	JOIN PCODNACAO ON (
		PCODNACAO.CODCLIENTE=PPESSOA.NACIONALIDADE
	)

WHERE 1=1
	AND PFUNC.CODSITUACAO <> 'D'
	AND PPESSOA.NACIONALIDADE <> 10
