SELECT 
	PFCODFIX.CODCOLIGADA,
	GCOLIGADA.NOMEFANTASIA AS COLIGADA,
	PFCODFIX.CHAPA,
	PFUNC.NOME AS COLABORADOR,
	PFUNC.CODSECAO,
	PSECAO.DESCRICAO AS SECAO,
	PFUNC.CODFUNCAO,
	PFUNCAO.NOME AS FUNCAO,
	PFCODFIX.VALOR,
	PFCODFIX.NROVEZES,
	DATEFROMPARTS(
		YEAR(PFCODFIX.RECCREATEDON),
		MONTH(PFCODFIX.RECCREATEDON),
		1
	) AS INICIO,
	EOMONTH(DATEADD(MONTH, 2, PFCODFIX.RECCREATEDON)) AS FIM

FROM PFCODFIX 
	JOIN GCOLIGADA ON (
		GCOLIGADA.CODCOLIGADA=PFCODFIX.CODCOLIGADA
	)
	JOIN PFUNC ON (
		PFUNC.CODCOLIGADA=PFCODFIX.CODCOLIGADA AND
		PFUNC.CHAPA=PFCODFIX.CHAPA
	)
	JOIN PSECAO ON (
		PSECAO.CODCOLIGADA=PFUNC.CODCOLIGADA AND
		PSECAO.CODIGO=PFUNC.CODSECAO
	)
	JOIN PFUNCAO ON (
		PFUNCAO.CODCOLIGADA=PFUNC.CODCOLIGADA AND
		PFUNCAO.CODIGO=PFUNC.CODFUNCAO
	)

WHERE 1=1
	AND PFCODFIX.CODEVENTO = '9161'

ORDER BY
	PFCODFIX.NROVEZES DESC,
	PFCODFIX.RECCREATEDON DESC
