SELECT 
	 PFCODFIX.CODCOLIGADA,
	 PFCODFIX.CHAPA,
	 PFCODFIX.CODEVENTO,
	 PEVENTO.DESCRICAO,
	 PFCODFIX.VALOR,
	 PFCODFIX.NROVEZES,
	 PFCODFIX.RECCREATEDON,
	 PFCODFIX.RECMODIFIEDON

FROM PFCODFIX 
	JOIN PEVENTO ON PEVENTO.CODCOLIGADA = PFCODFIX.CODCOLIGADA AND PEVENTO.CODIGO = PFCODFIX.CODEVENTO
	
WHERE 1=1
	AND PFCODFIX.CODEVENTO = '9161'

ORDER BY
	PFCODFIX.NROVEZES DESC
