SELECT 
	 PFCODFIX.CODCOLIGADA,
	 PFCODFIX.CHAPA,
	 PFCODFIX.VALOR,
	 PFCODFIX.NROVEZES,
	 PFCODFIX.RECCREATEDON,
	 PFCODFIX.RECMODIFIEDON

FROM PFCODFIX 
	
WHERE 1=1
	AND PFCODFIX.CODEVENTO = '9161'

ORDER BY
	PFCODFIX.NROVEZES DESC,
	PFCODFIX.RECCREATEDON DESC
