SELECT
    PFUNC.CODCOLIGADA AS COLIGADA,
    PFUNC.CHAPA,
    PFUNC.CODSECAO,
    PSECAO.DESCRICAO AS SECAO,
    PFUNC.CODFUNCAO,
    PFUNCAO.NOME AS FUNCAO,
    PFUNC.CODSITUACAO,
    PCODSITUACAO.DESCRICAO AS SITUACAO,
    PFUNC.DATAADMISSAO,
    PFUNC.DATADEMISSAO

FROM PFUNC (NOLOCK)
    JOIN GCOLIGADA (NOLOCK) ON ( 
	    GCOLIGADA.CODCOLIGADA=PFUNC.CODCOLIGADA
    )
    JOIN PSECAO (NOLOCK) ON (
        PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND 
        PSECAO.CODIGO = PFUNC.CODSECAO
    )
    JOIN PFUNCAO (NOLOCK) ON (
        PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA AND 
        PFUNC.CODFUNCAO = PFUNCAO.CODIGO
    )
    JOIN PCODSITUACAO (NOLOCK) ON (
	    PCODSITUACAO.CODCLIENTE=PFUNC.CODSITUACAO
    )
