table Afastados
	lineageTag: 114ce549-6923-46ec-9df8-e8b495e22c6f

	column CODCOLIGADA
		dataType: string
		lineageTag: 1c2c8449-9237-4a99-b314-07abc753623f
		summarizeBy: none
		sourceColumn: CODCOLIGADA

		annotation SummarizationSetBy = Automatic

	column NOMEFANTASIA
		dataType: string
		lineageTag: cb258b38-4af8-46ee-95b3-c1f6be7a6f1b
		summarizeBy: none
		sourceColumn: NOMEFANTASIA

		annotation SummarizationSetBy = Automatic

	column DTINICIO
		dataType: dateTime
		formatString: Short Date
		lineageTag: ee1e24ac-c270-408c-93ce-4aec1ac39a62
		summarizeBy: none
		sourceColumn: DTINICIO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CODPESSOA
		dataType: string
		lineageTag: a223fb08-e488-4ee2-8a87-af92b979ec84
		summarizeBy: none
		sourceColumn: CODPESSOA

		annotation SummarizationSetBy = Automatic

	column CHAPA
		dataType: string
		lineageTag: 336e029d-7db1-4ed5-b4d0-aec5179190f9
		summarizeBy: none
		sourceColumn: CHAPA

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: a4b95fd5-da12-4262-8f57-fcc9b6fe9b83
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column TIPO
		dataType: string
		lineageTag: c6903157-7f51-46fc-86dd-114865eb8b0d
		summarizeBy: none
		sourceColumn: TIPO

		annotation SummarizationSetBy = Automatic

	column SITUACAO
		dataType: string
		lineageTag: 9fda19c3-0ceb-4557-b569-54194be46dcb
		summarizeBy: none
		sourceColumn: SITUACAO

		annotation SummarizationSetBy = Automatic

	column SECAO
		dataType: string
		lineageTag: 9a80e797-1dff-4926-ae56-87d31b2c98e6
		summarizeBy: none
		sourceColumn: SECAO

		annotation SummarizationSetBy = Automatic

	column NOMETIPO = ```
			
			SWITCH(
			    'Afastados'[TIPO],
			    "T", "Ac. de Trabalho",
			    "P", "Previdência"
			)
			
			```
		lineageTag: 5c627ed9-f3f2-484e-9216-16eb0a33c780
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Afastados = m
		mode: import
		source =
				let
				    Source = Sql.Database("192.168.42.153", "corpore", [Query="SELECT #(lf)        PFHSTAFT.CODCOLIGADA, #(lf)        NOMEFANTASIA,#(lf)        PFUNC.CODPESSOA,#(lf)        PFUNC.CHAPA,#(lf)        PPESSOA.NOME,#(lf)        PCODSITUACAO.DESCRICAO AS SITUACAO,#(lf)        PSECAO.DESCRICAO AS SECAO,#(lf)        PFHSTAFT.TIPO,#(lf)        DTINICIO#(lf)#(lf)FROM PFHSTAFT #(lf)        JOIN GCOLIGADA ON #(lf)                GCOLIGADA.CODCOLIGADA = PFHSTAFT.CODCOLIGADA#(lf)        JOIN PFUNC ON #(lf)                PFUNC.CODCOLIGADA = PFHSTAFT.CODCOLIGADA#(lf)                AND PFUNC.CHAPA = PFHSTAFT.CHAPA#(lf)        LEFT JOIN PPESSOA ON #(lf)                PPESSOA.CODIGO=PFUNC.CODPESSOA#(lf)        JOIN PSECAO ON #(lf)#(tab)#(tab)#(tab)#(tab)PSECAO.CODIGO=PFUNC.CODSECAO #(lf)#(tab)#(tab)#(tab)#(tab)AND PSECAO.CODCOLIGADA=PFUNC.CODCOLIGADA#(lf)#(tab)#(tab)JOIN PCODSITUACAO ON #(lf)#(tab)#(tab)#(tab)#(tab)PCODSITUACAO.CODCLIENTE=PFUNC.CODSITUACAO#(lf)        #(lf)WHERE TIPO IN ('P','T')"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"DTINICIO", type date}, {"CODCOLIGADA", type text}, {"CODPESSOA", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

