table Metricas
	lineageTag: 486b2cb6-4d63-4300-ae2c-a731b5e1d11c

	measure TotalJustificativas = COUNTROWS(Atestados)
		formatString: 0
		lineageTag: d5157145-8503-4865-b15c-b380f8479850

	measure TotalColaboradores = DISTINCTCOUNT(Atestados[CPF])
		formatString: 0
		lineageTag: 05aac298-bb72-4695-a142-86ff6fbeb230

	measure AfastadosPrevidenciaAtualmente = ```
			
			COALESCE(
			    CALCULATE(
			        COUNTROWS(AfastadosAtuais),
			        AfastadosAtuais[CODSITUACAO] = "P"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 7db22a7a-ea90-483a-99c4-8e983294483c

	measure TotalCIDs = COUNT(Atestados[CID])
		formatString: 0
		lineageTag: a478f07f-ce16-4a00-acc9-76cb7b6e6832

	measure TotalAfastados = COUNTROWS(Afastados)
		formatString: 0
		lineageTag: 6ac06e8f-7865-45ca-9218-9e78686fd71a

	measure AfastadosAcidenteAtualmente = ```
			
			COALESCE(
			    CALCULATE(
			        COUNTROWS(AfastadosAtuais),
			        AfastadosAtuais[CODSITUACAO] = "T"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 9712f652-4e1c-4983-b23a-e525a99754a9

	measure AfastadosAcidenteTotal = ```
			
			CALCULATE(
			    COUNTROWS(Afastados),
			    Afastados[TIPO] = "T"
			)
			
			```
		formatString: 0
		lineageTag: 32c49b68-5b47-4e58-b14d-6bf5ae271b5d

	measure AfastadosPrevidenciaTotal = ```
			
			CALCULATE(
			    COUNTROWS(Afastados),
			    Afastados[TIPO] = "P"
			)
			
			```
		formatString: 0
		lineageTag: 6341b3fd-433c-48fe-a7a5-07b6a7f93cf5

	measure TotalAtestados = ```
			
			COALESCE(
			    CALCULATE(
			        COUNTROWS(Atestados),
			        Atestados[CATEGORIA_ATESTADO] = "Atestado"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 13fec51e-27ed-4a5f-a766-5298251def57

	measure TotalDeclaracoes = ```
			
			COALESCE(
			    CALCULATE(
			        COUNTROWS(Atestados),
			        Atestados[CATEGORIA_ATESTADO] = "Declaração"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 7c1aa9c6-424c-4511-b771-4c3e42e958e8

	partition Metricas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

