table Metricas
	lineageTag: 486b2cb6-4d63-4300-ae2c-a731b5e1d11c

	measure TotalJustificativas = ```
			
			CALCULATE(
			    COUNTROWS(Atestados),
			    NOT(ISBLANK(Atestados[DTINICIO]))
			)
			
			```
		formatString: 0
		lineageTag: d5157145-8503-4865-b15c-b380f8479850

	measure TotalColaboradoresComAtestado = ```
			
			CALCULATE(
			    DISTINCTCOUNT(Atestados[COLIGADACOLABORADOR]),
			    NOT(ISBLANK(Atestados[DTINICIO]))
			)
			
			```
		formatString: 0
		lineageTag: 05aac298-bb72-4695-a142-86ff6fbeb230

	measure AfastadosPrevidenciaAtualmente = ```
			
			COALESCE(
			    CALCULATE(
			        COUNTROWS(AfastadosAtuais),
			        AfastadosAtuais[CODSITUACAO] = "P"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 7db22a7a-ea90-483a-99c4-8e983294483c

	measure TotalCIDs = ```
			
			CALCULATE(
			    COUNT(Atestados[CID]),
			    NOT(ISBLANK(Atestados[DTINICIO]))
			)
			
			```
		formatString: 0
		lineageTag: a478f07f-ce16-4a00-acc9-76cb7b6e6832

	measure TotalAfastados = COUNTROWS(Afastados)
		formatString: 0
		lineageTag: 6ac06e8f-7865-45ca-9218-9e78686fd71a

	measure AfastadosAcidenteAtualmente = ```
			
			COALESCE(
			    CALCULATE(
			        COUNTROWS(AfastadosAtuais),
			        AfastadosAtuais[CODSITUACAO] = "T"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 9712f652-4e1c-4983-b23a-e525a99754a9

	measure AfastadosAcidenteTotal = ```
			
			CALCULATE(
			    DISTINCTCOUNT(Afastados[CODPESSOA]),
			    Afastados[TIPO] = "T"
			)
			
			```
		formatString: 0
		lineageTag: 32c49b68-5b47-4e58-b14d-6bf5ae271b5d

	measure AfastadosPrevidenciaTotal = ```
			
			CALCULATE(
			    DISTINCTCOUNT(Afastados[CODPESSOA]),
			    Afastados[TIPO] = "P"
			)
			
			```
		formatString: 0
		lineageTag: 6341b3fd-433c-48fe-a7a5-07b6a7f93cf5

	measure TotalAtestados = ```
			
			CALCULATE(
			    COUNTROWS(Atestados),
			    FILTER(
			        Atestados,
			        NOT(ISBLANK(Atestados[DTINICIO])) &&
			        Atestados[CATEGORIA_ATESTADO] = "Atestado"
			    )
			)
			
			```
		formatString: 0
		lineageTag: 13fec51e-27ed-4a5f-a766-5298251def57

	measure TotalDeclaracoes = ```
			
			CALCULATE(
			    COUNTROWS(Atestados),
			    FILTER(
			        Atestados,
			        NOT(ISBLANK(Atestados[DTINICIO])) &&
			        Atestados[CATEGORIA_ATESTADO] = "Declaração"
			    )
			)
			
			```
		formatString: 0
		lineageTag: 7c1aa9c6-424c-4511-b771-4c3e42e958e8

	measure JustificativasPorColaborador = ([TotalJustificativas] / ([TotalColaboradores]))
		formatString: 0.0
		lineageTag: 3194ada9-38fb-4fa7-8c09-483a71f29adf

	measure TotalColaboradoresSemAtestado = ```
			
			CALCULATE(
			    DISTINCTCOUNT(Atestados[COLIGADACOLABORADOR]),
			    ISBLANK(Atestados[DTINICIO]),
			    REMOVEFILTERS(Calendario[Date])
			)
			
			```
		formatString: 0
		lineageTag: 2d93d97f-2173-471e-8f17-fcd73b1cd509

	measure TotalDiasAtestados = ```
			
			CALCULATE(
			    SUM(Atestados[DIASATESTADOS]),
			    FILTER(
			        Atestados,
			        NOT(ISBLANK(Atestados[DIASATESTADOS])) &&
			        Atestados[CATEGORIA_ATESTADO] = "Atestado"
			    )
			)
			
			```
		formatString: 0
		lineageTag: 98dd3d9b-47e1-46a0-90ba-4b81b8207289

	measure TotalDiasDeclaracoes = ```
			
			CALCULATE(
			    SUM(Atestados[DIASATESTADOS]),
			    FILTER(
			        Atestados,
			        NOT(ISBLANK(Atestados[DIASATESTADOS])) &&
			        Atestados[CATEGORIA_ATESTADO] = "Declaração"
			    )
			)
			
			```
		formatString: 0
		lineageTag: 39e067ba-94fe-442d-8930-da3691e05b3e

	measure TotalDiasJustificativas = ```
			
			CALCULATE(
			    SUM(Atestados[DIASATESTADOS]),
			    FILTER(
			        Atestados,
			        NOT(ISBLANK(Atestados[DIASATESTADOS]))
			    )
			)
			
			```
		formatString: 0
		lineageTag: 9fcb0ff3-4113-456e-8103-845fd5a1ee6d

	measure TotalColaboradores = ```
			
			CALCULATE(
			    DISTINCTCOUNT(Atestados[COLIGADACOLABORADOR]),
			    Atestados[COLIGADACOLABORADOR] <> "-",
			    REMOVEFILTERS(Calendario[Date])
			)
			
			```
		formatString: 0
		lineageTag: 9afbd1ac-e15a-42ed-b099-155fcc0ec409

	measure DiasAfastadosPorColaborador = ([TotalDiasJustificativas] / ([TotalColaboradores]))
		formatString: 0.0
		lineageTag: ad293980-5b37-44a1-aa76-7df7d7e6f3f7

	partition Metricas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

