table Medidas
	lineageTag: 733e11e8-36db-4af0-b7f6-333061c272ee

	measure ADMISSOES = ```
			
			COALESCE(
			    CALCULATE(
			        COUNTROWS(Funcionarios),
			        USERELATIONSHIP(Funcionarios[DATAADMISSAO], Calendario[Date])
			    ),
			    0   
			)
			
			```
		formatString: 0
		lineageTag: 6078b883-f360-4a79-b582-871af8be38ac

	measure DEMISSOES = ```
			
			VAR Ref = IF(MAX(Calendario[Date]) > TODAY(), TODAY(), MAX(Calendario[Date])) RETURN
			
			COALESCE(
			    CALCULATE(
			        COUNTROWS(Funcionarios),
			        Funcionarios[DATADEMISSAO] <= Ref,
			        USERELATIONSHIP(Funcionarios[DATADEMISSAO], Calendario[Date])
			    ),
			    0   
			)
			
			```
		formatString: 0
		lineageTag: 9f3a0fe8-d21a-451a-84d4-a22fd6e47dc3

	measure TOTALCOLABORADORES = ```
			
			COUNTROWS (
			    FILTER (
			        ALL (Funcionarios),
			        Funcionarios[DATAADMISSAO] <= MAX(Calendario[Date]) &&
			        (
			            ISBLANK (Funcionarios[DATADEMISSAO]) || Funcionarios[DATADEMISSAO] > MAX(Calendario[Date])
			        )
			    )
			)
			
			```
		formatString: 0
		lineageTag: 41cb038d-5044-4adf-9930-e51b8df15fc6

	measure TURNOVER = (([ADMISSOES] + [DEMISSOES]) / 2) / [TOTALCOLABORADORES]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 34ce0d30-39a0-4977-b89e-5a70660ae6f3

	partition Medidas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

