table Medidas
	lineageTag: 733e11e8-36db-4af0-b7f6-333061c272ee

	measure ADMISSOES = ```
			
			COALESCE(
			    CALCULATE(
			        COUNTROWS(Funcionarios),
			        USERELATIONSHIP(Funcionarios[DATAADMISSAO], Calendario[Date])
			    ),
			    0   
			)
			
			```
		formatString: 0
		lineageTag: 6078b883-f360-4a79-b582-871af8be38ac

	measure DEMISSOES = ```
			
			VAR Ref = IF(MAX(Calendario[Date]) > TODAY(), TODAY(), MAX(Calendario[Date])) RETURN
			
			COALESCE(
			    CALCULATE(
			        COUNTROWS(Funcionarios),
			        NOT ISBLANK(Funcionarios[DATADEMISSAO]) && Funcionarios[DATADEMISSAO] <= Ref,
			        USERELATIONSHIP(Funcionarios[DATADEMISSAO], Calendario[Date])
			    ),
			    0   
			)
			
			```
		formatString: 0
		lineageTag: 9f3a0fe8-d21a-451a-84d4-a22fd6e47dc3

	measure ATIVOS_FIM_PERIODO = ```
			
			VAR Ref = 
			    IF(
			        MAX(Calendario[Date]) > TODAY(), 
			        TODAY(), 
			        MAX(Calendario[Date])
			    ) 
			
			RETURN
			COALESCE(
			    CALCULATE(
			        COUNTROWS(Funcionarios),
			        Funcionarios[DATAADMISSAO] <= Ref && 
			        (
			            ISBLANK(Funcionarios[DATADEMISSAO]) || 
			            Funcionarios[DATADEMISSAO] > Ref
			        ),
			        REMOVEFILTERS(Calendario)
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 41cb038d-5044-4adf-9930-e51b8df15fc6

	measure TURNOVER = (([ADMISSOES] + [DEMISSOES]) / 2) / [ATIVOS_FIM_PERIODO]
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 34ce0d30-39a0-4977-b89e-5a70660ae6f3

	measure ATIVOS_INICIO_PERIODO = ```
			
			VAR Ref = 
			    IF(
			        MIN(Calendario[Date]) > TODAY(), 
			        TODAY(), 
			        MIN(Calendario[Date])
			    ) 
			
			RETURN
			COALESCE(
			    CALCULATE(
			        COUNTROWS(Funcionarios),
			        Funcionarios[DATAADMISSAO] <= Ref && 
			        (
			            ISBLANK(Funcionarios[DATADEMISSAO]) || 
			            Funcionarios[DATADEMISSAO] > Ref
			        ),
			        REMOVEFILTERS(Calendario)
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 423fdf0a-692a-46a4-9a0a-3f5b164c2af0

	measure TURNOVER_V2 = ([DEMISSOES] / (([ATIVOS_INICIO_PERIODO] + [ATIVOS_FIM_PERIODO]) / 2))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 65553983-8cfe-46a1-a13b-3de68b73a8d3

	partition Medidas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

