SELECT 
	VOCORRENCIA.CODCOLIGADA,
	VOCORRENCIA.CHAPA,
	VOCORRENCIA.CODOCORRENCIA,
	VPPRAFONTEGERA.NOME AS CAUSA,
	VNATUREZACAT.NATUREZA AS LESAO

FROM VOCORRENCIA
	LEFT JOIN VPPRAFONTEGERA ON (
		VPPRAFONTEGERA.CODFONTEGERA=VOCORRENCIA.CODSITUACAOGERA
	)
	LEFT JOIN VOCORRENCIANATUREZAMEDICA VONM ON (
		VONM.CODCOLIGADA=VOCORRENCIA.CODCOLIGADA AND
		VONM.CODOCORRENCIA=VOCORRENCIA.CODOCORRENCIA
	)
	LEFT JOIN VNATUREZACAT ON (
		VNATUREZACAT.CODNATUREZA = VONM.CODNATUREZA
	)
