SET DATEFIRST 7;

WITH DATAS AS (
    SELECT 
        DATEADD(
            DAY,
            ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) - 1,
            DATEFROMPARTS(
                YEAR(GETDATE()), 
                MONTH(GETDATE()), 
                1
            )
        ) AS DATA
    FROM sys.objects
)

SELECT
    ((SELECT COUNT(*) FROM DATAS WHERE DATA <= EOMONTH(GETDATE()) AND DATEPART(WEEKDAY, DATA) BETWEEN 2 AND 6) * 8) + ((SELECT COUNT(*) FROM DATAS WHERE DATA <= EOMONTH(GETDATE()) AND DATEPART(WEEKDAY, DATA) = 7) * 4) AS HORASTRAB,
    (SELECT COALESCE(SUM(REF), 0) FROM PFMOVCC WHERE CODEVENTO = '0082' AND MESCOMP = MONTH(GETDATE()) AND ANOCOMP = YEAR(GETDATE())) AS HORASEXTRAS,
    (SELECT COUNT(*) FROM PFUNC WHERE CODSITUACAO IN ('F','P','T','E')) AS AFASTADOS,
    (SELECT COUNT(*) FROM PFUNC WHERE CODSITUACAO <> 'D') AS TOTALFUNC
