SELECT 
		PFUNC.CODCOLIGADA, 
		PFUNC.CHAPA, 
		PFUNC.NOME, 
		PFUNC.CODSITUACAO,
		PSECAO.DESCRICAO AS SECAO 

FROM PFUNC 
		JOIN PSECAO ON
				PSECAO.CODCOLIGADA=PFUNC.CODCOLIGADA
			AND PSECAO.CODIGO=PFUNC.CODSECAO
WHERE 1=1
	AND CODSITUACAO IN ('T','P')