SELECT	
		VATESTADO.CODCOLIGADA,
		PFUNC.CODCOLIGADA AS CODCOLIGADAREF,
		GCOLIGADA.NOMEFANTASIA AS COLIGADA,
		VATESTADO.CODPESSOA,
		PFUNC.CODPESSOA AS CODPESSOAREF,
		VCHAPAATESTADO.CHAPA,
		PFUNC.CHAPA AS CHAPAREF,
		PPESSOA.NOME AS COLABORADOR,
		PPESSOA.CPF,
		PSECAO.DESCRICAO AS SECAO,
		PCODSITUACAO.DESCRICAO AS SITUACAO,
		VTIPOATESTADO.CODTPATESTADO,
		VTIPOATESTADO.NOMETPATESTADO AS TIPOATESTADO,
		VATESTADO.DTINICIO,
		VATESTADO.DTFINAL AS DTFIM,
		DATEDIFF(DAY, VATESTADO.DTINICIO, VATESTADO.DTFINAL) + 1 AS DIASATESTADOS,
		VCID.CID AS CODCID,
		VCID.DESCRICAOCID AS CID
		
FROM VATESTADO
		JOIN VTIPOATESTADO ON 
				VTIPOATESTADO.CODTPATESTADO=VATESTADO.CODTPATESTADO
		LEFT JOIN VCID ON 
				VCID.CID=VATESTADO.CID
		LEFT JOIN VCHAPAATESTADO ON 
				VATESTADO.CODPESSOA=VCHAPAATESTADO.CODPESSOA 
				AND VATESTADO.SEQATESTADO=VCHAPAATESTADO.SEQATESTADO 
				AND VATESTADO.DTINICIO=VCHAPAATESTADO.DTINICIO 
				AND VATESTADO.CODTPATESTADO=VCHAPAATESTADO.CODTPATESTADO
		JOIN GCOLIGADA ON 
				GCOLIGADA.CODCOLIGADA=VATESTADO.CODCOLIGADA
		JOIN PPESSOA ON 
				PPESSOA.CODIGO=VATESTADO.CODPESSOA
		FULL JOIN PFUNC ON
				PFUNC.CODCOLIGADA=VCHAPAATESTADO.CODCOLIGADA
				AND PFUNC.CHAPA=VCHAPAATESTADO.CHAPA
		LEFT JOIN PSECAO ON 
				PSECAO.CODIGO=PFUNC.CODSECAO 
				AND PSECAO.CODCOLIGADA=PFUNC.CODCOLIGADA
		LEFT JOIN PCODSITUACAO ON 
				PCODSITUACAO.CODCLIENTE=PFUNC.CODSITUACAO

ORDER BY 
		PPESSOA.NOME,
		VATESTADO.DTINICIO
