WITH TEMPTABLE AS (
    SELECT	
        VATESTADO.CODCOLIGADA,
        VCID.CID,
        VATESTADO.CODPESSOA,
        VCHAPAATESTADO.CHAPA,
        PPESSOA.NOME AS COLABORADOR,
        PCODSITUACAO.DESCRICAO AS SITUACAO,
        VATESTADO.DTINICIO,
        CASE
            WHEN VATESTADO.DTFINAL IS NULL THEN CAST(GETDATE() AS DATE)
            ELSE VATESTADO.DTFINAL 
        END AS DTFIM,
        DATEDIFF(
            DAY, 
            VATESTADO.DTINICIO, 
            CASE
                WHEN VATESTADO.DTFINAL IS NULL THEN CAST(GETDATE() AS DATE)
                ELSE VATESTADO.DTFINAL 
            END
        ) + 1 AS DIASATESTADOS
        
    FROM VATESTADO
    JOIN VTIPOATESTADO ON 
        VTIPOATESTADO.CODTPATESTADO=VATESTADO.CODTPATESTADO
    LEFT JOIN VCID ON 
        VCID.CID=VATESTADO.CID
    LEFT JOIN VCHAPAATESTADO ON 
        VATESTADO.CODPESSOA=VCHAPAATESTADO.CODPESSOA 
        AND VATESTADO.SEQATESTADO=VCHAPAATESTADO.SEQATESTADO 
        AND VATESTADO.DTINICIO=VCHAPAATESTADO.DTINICIO 
        AND VATESTADO.CODTPATESTADO=VCHAPAATESTADO.CODTPATESTADO
    JOIN PPESSOA ON 
        PPESSOA.CODIGO=VATESTADO.CODPESSOA
    LEFT JOIN PFUNC ON
        PFUNC.CODCOLIGADA=VCHAPAATESTADO.CODCOLIGADA
        AND PFUNC.CHAPA=VCHAPAATESTADO.CHAPA
    LEFT JOIN PSECAO ON 
        PSECAO.CODIGO=PFUNC.CODSECAO 
        AND PSECAO.CODCOLIGADA=PFUNC.CODCOLIGADA
    LEFT JOIN PCODSITUACAO ON 
        PCODSITUACAO.CODCLIENTE=PFUNC.CODSITUACAO

    WHERE CODSITUACAO NOT IN ('D','T','P','C')
),
ORDENADO AS (
    SELECT 
        *,
        LAG(DTFIM) OVER (
            PARTITION BY CODCOLIGADA, CODPESSOA, CHAPA, CID 
            ORDER BY DTINICIO
        ) AS DTFIM_ANTERIOR
    FROM TEMPTABLE
    WHERE DTFIM >= CAST(GETDATE() AS DATE)
),
COM_GRUPO AS (
    SELECT 
        *,
        CASE 
            WHEN DTFIM_ANTERIOR IS NULL THEN 1
            WHEN DATEDIFF(DAY, DTFIM_ANTERIOR, DTINICIO) <= 60 THEN 0
            ELSE 1
        END AS NOVO_GRUPO
    FROM ORDENADO
),
GRUPOS_IDENTIFICADOS AS (
    SELECT 
        *,
        SUM(NOVO_GRUPO) OVER (
            PARTITION BY CODCOLIGADA, CODPESSOA, CHAPA, CID 
            ORDER BY DTINICIO
            ROWS UNBOUNDED PRECEDING
        ) AS GRUPO_ID
    FROM COM_GRUPO
)
SELECT 
    CODCOLIGADA,
    CID,
    CODPESSOA,
    CHAPA,
    COLABORADOR,
    SITUACAO,
    MIN(DTINICIO) AS DTINICIO_PRIMEIRO,
    MAX(DTFIM) AS DTFIM_ULTIMO,
    SUM(DIASATESTADOS) AS TOTAL_DIAS_ATESTADOS,
    COUNT(*) AS QTD_ATESTADOS
FROM GRUPOS_IDENTIFICADOS
GROUP BY 
    CODCOLIGADA, 
    CID, 
    CODPESSOA, 
    CHAPA, 
    COLABORADOR,
    SITUACAO,
    GRUPO_ID
ORDER BY 
    TOTAL_DIAS_ATESTADOS DESC