SELECT 
        PFHSTAFT.CODCOLIGADA, 
        NOMEFANTASIA,
        PFUNC.CODPESSOA,
        PFUNC.CHAPA,
        PPESSOA.NOME,
        PCODSITUACAO.DESCRICAO AS SITUACAO,
        PSECAO.DESCRICAO AS SECAO,
        PFHSTAFT.TIPO,
        DTINICIO

FROM PFHSTAFT 
        JOIN GCOLIGADA ON 
                GCOLIGADA.CODCOLIGADA = PFHSTAFT.CODCOLIGADA
        JOIN PFUNC ON 
                PFUNC.CODCOLIGADA = PFHSTAFT.CODCOLIGADA
                AND PFUNC.CHAPA = PFHSTAFT.CHAPA
        LEFT JOIN PPESSOA ON 
                PPESSOA.CODIGO=PFUNC.CODPESSOA
        JOIN PSECAO ON 
				PSECAO.CODIGO=PFUNC.CODSECAO 
				AND PSECAO.CODCOLIGADA=PFUNC.CODCOLIGADA
		JOIN PCODSITUACAO ON 
				PCODSITUACAO.CODCLIENTE=PFUNC.CODSITUACAO
        
WHERE TIPO IN ('P','T')