table Asos
	lineageTag: f3cabdf7-bea2-4bc2-9a6b-2d5fd5737ed1

	column CODCOLIGADA
		dataType: string
		lineageTag: b5f6ca72-5e0a-4fa3-955d-2e03b28f8dc6
		summarizeBy: none
		sourceColumn: CODCOLIGADA

		annotation SummarizationSetBy = Automatic

	column CHAPA
		dataType: string
		lineageTag: 2eac1f7e-9882-442f-936c-675079559c1c
		summarizeBy: none
		sourceColumn: CHAPA

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 06ba8a47-7f12-47d4-b9ea-691bd5227b2d
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column CODSECAO
		dataType: string
		lineageTag: 76ff034e-8957-433a-a97b-c5d4737f26ec
		summarizeBy: none
		sourceColumn: CODSECAO

		annotation SummarizationSetBy = Automatic

	column SECAO
		dataType: string
		lineageTag: 6d89fd46-386a-4a18-a0aa-496e2fda6911
		summarizeBy: none
		sourceColumn: SECAO

		annotation SummarizationSetBy = Automatic

	column CODFUNCAO
		dataType: string
		lineageTag: eb85d46f-f66a-476d-a6d1-d79680483458
		summarizeBy: none
		sourceColumn: CODFUNCAO

		annotation SummarizationSetBy = Automatic

	column FUNCAO
		dataType: string
		lineageTag: a0ca6ce8-ed81-4d80-a650-687087beec85
		summarizeBy: none
		sourceColumn: FUNCAO

		annotation SummarizationSetBy = Automatic

	column CODSITUACAO
		dataType: string
		lineageTag: 101c63d0-ec5f-4acc-b1c4-2df3538abbcf
		summarizeBy: none
		sourceColumn: CODSITUACAO

		annotation SummarizationSetBy = Automatic

	column SITUACAO
		dataType: string
		lineageTag: 671e9117-8dd7-4567-afaf-8c0068211606
		summarizeBy: none
		sourceColumn: SITUACAO

		annotation SummarizationSetBy = Automatic

	column CODPERFIL
		dataType: string
		lineageTag: fbbeaa11-11f4-4bff-814d-e8866145ec5e
		summarizeBy: none
		sourceColumn: CODPERFIL

		annotation SummarizationSetBy = Automatic

	column NOMEPERFIL
		dataType: string
		lineageTag: 16d599ad-4bc3-470f-b9b7-cdaf20070e2e
		summarizeBy: none
		sourceColumn: NOMEPERFIL

		annotation SummarizationSetBy = Automatic

	column CODEXAME
		dataType: string
		lineageTag: 834ef9b7-f586-44e4-8984-2708ecd5164d
		summarizeBy: none
		sourceColumn: CODEXAME

		annotation SummarizationSetBy = Automatic

	column NOMEEXAME
		dataType: string
		lineageTag: 70cbcfe4-88d9-44c4-acad-de0c9426b7d8
		summarizeBy: none
		sourceColumn: NOMEEXAME

		annotation SummarizationSetBy = Automatic

	column TIPOEXAME
		dataType: string
		lineageTag: b9397f60-b832-404f-92eb-baaf00d439ad
		summarizeBy: none
		sourceColumn: TIPOEXAME

		annotation SummarizationSetBy = Automatic

	column NOMETIPOEXAME
		dataType: string
		lineageTag: 22500b77-1bf5-41ba-b5c0-7ac2da459ac2
		summarizeBy: none
		sourceColumn: NOMETIPOEXAME

		annotation SummarizationSetBy = Automatic

	column DATAEXAME
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0b7d1b57-c051-413d-995d-3f0748191d78
		summarizeBy: none
		sourceColumn: DATAEXAME

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SITUACAOEXAME
		dataType: string
		lineageTag: b7f0df96-affa-4c2d-a2ee-3f5268eb5b5d
		summarizeBy: none
		sourceColumn: SITUACAOEXAME

		annotation SummarizationSetBy = Automatic

	column VALIDADE = ```
			
			VAR DataRef = Asos[DATAEXAME]
			VAR Dias = DATEDIFF(TODAY(), DataRef, DAY)
			RETURN
			SWITCH(
			    TRUE(),
			    ISBLANK(DataRef), "Pendente",
			    Dias < 0, "Vencido",
			    Dias <= 60, "A Vencer",
			    Dias > 60, "Em Dia"
			)
			
			```
		lineageTag: 6370701f-e9f8-4e15-b7f9-102cbaa93540
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column NOMEFANTASIA
		dataType: string
		lineageTag: 0986e513-d464-47cb-b5da-2d1958fa4846
		summarizeBy: none
		sourceColumn: NOMEFANTASIA

		annotation SummarizationSetBy = Automatic

	partition Asos = m
		mode: import
		source =
				let
				    Source = Sql.Database("192.168.42.153", "corpore", [Query="WITH PERFIS AS (#(lf)#(tab)#(tab)SELECT DISTINCT#(lf)#(tab)#(tab)#(tab)#(tab)VPERFIL.CODCOLIGADA,#(lf)#(tab)#(tab)#(tab)#(tab)VPERFIL.CODPERFIL,#(lf)#(tab)#(tab)#(tab)#(tab)VPERFIL.NOMEPERFIL,#(lf)#(tab)#(tab)#(tab)#(tab)VBATERIAEXAMES.CODEXAME,#(lf)#(tab)#(tab)#(tab)#(tab)VEXAMES.NOMEEXAME#(lf)#(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab)FROM VPERFIL#(lf)#(tab)#(tab)#(tab)#(tab)JOIN VBATERIAEXAMES ON#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)VBATERIAEXAMES.CODCOLIGADA=VPERFIL.CODCOLIGADA#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VBATERIAEXAMES.CODPERFIL=VPERFIL.CODPERFIL#(lf)#(tab)#(tab)#(tab)#(tab)JOIN VEXAMES (NOLOCK) ON#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)VEXAMES.CODCOLIGADA=VBATERIAEXAMES.CODCOLIGADA#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VEXAMES.CODEXAME=VBATERIAEXAMES.CODEXAME#(lf)),#(lf)#(lf)PERFILCOLABORADOR AS (#(lf)#(tab)#(tab)SELECT#(lf)#(tab)#(tab)#(tab)#(tab)PFUNC.CODCOLIGADA,#(lf)#(tab)#(tab)#(tab)#(tab)PFUNC.CHAPA,#(lf)#(tab)#(tab)#(tab)#(tab)(#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)SELECT TOP 1 #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)CODPERFIL #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)FROM VEXAMESPEND #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHERE 1=1#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AND CODCOLIGADA=PFUNC.CODCOLIGADA #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AND CODPESSOA=PFUNC.CODPESSOA #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AND CHAPA=PFUNC.CHAPA #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ORDER BY #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)DATAPROXEXAME DESC#(lf)#(tab)#(tab)#(tab)#(tab)) AS CODPERFIL#(lf)#(lf)#(tab)#(tab)FROM PFUNC #(lf)#(lf)#(tab)#(tab)WHERE 1=1#(lf)#(tab)#(tab)#(tab)#(tab)AND PFUNC.CODSITUACAO <> 'D'#(lf))#(lf)#(lf)SELECT #(lf)#(tab)#(tab)PERFILCOLABORADOR.CODCOLIGADA, #(lf)#(tab)#(tab)GCOLIGADA.NOMEFANTASIA,#(lf)#(tab)#(tab)PERFILCOLABORADOR.CHAPA, #(lf)#(tab)#(tab)PFUNC.NOME,#(lf)#(tab)#(tab)PFUNC.CODSECAO,#(lf)#(tab)#(tab)PSECAO.DESCRICAO AS SECAO,#(lf)#(tab)#(tab)PFUNC.CODFUNCAO,#(lf)#(tab)#(tab)PFUNCAO.NOME AS FUNCAO,#(lf)#(tab)#(tab)PFUNC.CODSITUACAO,#(lf)#(tab)#(tab)PCODSITUACAO.DESCRICAO AS SITUACAO,#(lf)#(tab)#(tab)PERFILCOLABORADOR.CODPERFIL, #(lf)#(tab)#(tab)PERFIS.NOMEPERFIL,#(lf)#(tab)#(tab)PERFIS.CODEXAME,#(lf)#(tab)#(tab)PERFIS.NOMEEXAME,#(lf)#(tab)#(tab)(#(lf)#(tab)#(tab)#(tab)#(tab)SELECT TOP 1 TIPOEXAME FROM VEXAMESPEND #(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab)#(tab)#(tab)WHERE 1=1#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VEXAMESPEND.CODCOLIGADA=PERFILCOLABORADOR.CODCOLIGADA#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VEXAMESPEND.CHAPA=PERFILCOLABORADOR.CHAPA#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND#(tab)VEXAMESPEND.CODPERFIL=PERFILCOLABORADOR.CODPERFIL#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND#(tab)VEXAMESPEND.CODEXAME=PERFIS.CODEXAME #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VEXAMESPEND.REALIZADO = 0#(lf)#(tab)#(tab)#(tab)#(tab)ORDER BY #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)DATAPROXEXAME DESC#(lf)#(tab)#(tab)) AS TIPOEXAME,#(lf)#(tab)#(tab)(#(lf)#(tab)#(tab)#(tab)#(tab)SELECT TOP 1 VTIPOEXAME.DESCRICAO FROM VEXAMESPEND#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)LEFT JOIN VTIPOEXAME (NOLOCK) ON#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)VTIPOEXAME.CODCLIENTE=VEXAMESPEND.TIPOEXAME#(lf)#(tab)#(tab)#(tab)#(tab)WHERE 1=1#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VEXAMESPEND.CODCOLIGADA=PERFILCOLABORADOR.CODCOLIGADA#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VEXAMESPEND.CHAPA=PERFILCOLABORADOR.CHAPA#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND#(tab)VEXAMESPEND.CODPERFIL=PERFILCOLABORADOR.CODPERFIL#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND#(tab)VEXAMESPEND.CODEXAME=PERFIS.CODEXAME #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VEXAMESPEND.REALIZADO = 0#(lf)#(tab)#(tab)#(tab)#(tab)ORDER BY #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)DATAPROXEXAME DESC#(lf)#(tab)#(tab)) AS NOMETIPOEXAME,#(lf)#(tab)#(tab)(#(lf)#(tab)#(tab)#(tab)#(tab)SELECT TOP 1 DATAPROXEXAME FROM VEXAMESPEND #(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab)#(tab)#(tab)WHERE 1=1#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VEXAMESPEND.CODCOLIGADA=PERFILCOLABORADOR.CODCOLIGADA#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VEXAMESPEND.CHAPA=PERFILCOLABORADOR.CHAPA#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND#(tab)VEXAMESPEND.CODPERFIL=PERFILCOLABORADOR.CODPERFIL#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND#(tab)VEXAMESPEND.CODEXAME=PERFIS.CODEXAME #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VEXAMESPEND.REALIZADO = 0#(lf)#(tab)#(tab)#(tab)#(tab)ORDER BY #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)DATAPROXEXAME DESC#(lf)#(tab)#(tab)) AS DATAEXAME,#(lf)#(tab)#(tab)(#(lf)#(tab)#(tab)#(tab)#(tab)SELECT TOP 1 REALIZADO FROM VEXAMESPEND #(tab)#(tab)#(tab)#(tab)#(lf)#(tab)#(tab)#(tab)#(tab)WHERE 1=1#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VEXAMESPEND.CODCOLIGADA=PERFILCOLABORADOR.CODCOLIGADA#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VEXAMESPEND.CHAPA=PERFILCOLABORADOR.CHAPA#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND#(tab)VEXAMESPEND.CODPERFIL=PERFILCOLABORADOR.CODPERFIL#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND#(tab)VEXAMESPEND.CODEXAME=PERFIS.CODEXAME #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND VEXAMESPEND.REALIZADO = 0#(lf)#(tab)#(tab)#(tab)#(tab)ORDER BY #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)DATAPROXEXAME DESC#(lf)#(tab)#(tab)) AS SITUACAOEXAME#(lf)#(lf)FROM PERFILCOLABORADOR #(lf)#(tab)#(tab)JOIN PERFIS ON #(lf)#(tab)#(tab)#(tab)#(tab)PERFIS.CODCOLIGADA=PERFILCOLABORADOR.CODCOLIGADA #(lf)#(tab)#(tab)#(tab)AND PERFIS.CODPERFIL=PERFILCOLABORADOR.CODPERFIL#(lf)#(tab)#(tab)JOIN GCOLIGADA ON #(lf)#(tab)#(tab)#(tab)#(tab)GCOLIGADA.CODCOLIGADA=PERFILCOLABORADOR.CODCOLIGADA #(lf)#(tab)#(tab)JOIN PFUNC ON #(lf)#(tab)#(tab)#(tab)#(tab)PFUNC.CODCOLIGADA=PERFILCOLABORADOR.CODCOLIGADA #(lf)#(tab)#(tab)#(tab)AND PFUNC.CHAPA=PERFILCOLABORADOR.CHAPA#(lf)#(tab)#(tab)JOIN PSECAO (NOLOCK) ON#(lf)#(tab)#(tab)#(tab)#(tab)PSECAO.CODIGO=PFUNC.CODSECAO#(lf)#(tab)#(tab)#(tab)AND PSECAO.CODCOLIGADA=PFUNC.CODCOLIGADA#(lf)#(tab)#(tab)JOIN PFUNCAO (NOLOCK) ON#(lf)#(tab)#(tab)#(tab)#(tab)PFUNCAO.CODIGO=PFUNC.CODFUNCAO#(lf)#(tab)#(tab)#(tab)AND PFUNCAO.CODCOLIGADA=PFUNC.CODCOLIGADA#(lf)#(tab)#(tab)JOIN PCODSITUACAO (NOLOCK) ON#(lf)#(tab)#(tab)#(tab)#(tab)PCODSITUACAO.CODCLIENTE=PFUNC.CODSITUACAO#(lf)#(lf)ORDER BY#(lf)#(tab)#(tab)PERFILCOLABORADOR.CODCOLIGADA,#(lf)#(tab)#(tab)PERFILCOLABORADOR.CHAPA#(lf)"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"CODCOLIGADA", type text}, {"DATAEXAME", type date}, {"SITUACAOEXAME", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

