table Metricas
	lineageTag: a16a904e-f54f-42b0-b0ba-74f24013478b

	measure 'Total de Exames Em Dia' = ```
			
			COALESCE(    
			    CALCULATE(
			        COUNTROWS(Asos),
			        Asos[VALIDADE] = "Em Dia"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 4b3b80a2-00c3-459c-8d61-f901c454af7a

	measure 'Total de Exames A Vencer' = ```
			
			COALESCE(    
			    CALCULATE(
			        COUNTROWS(Asos),
			        Asos[VALIDADE] = "A Vencer"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 81c8e370-0654-4223-8c3e-d7506f9035d4

	measure 'Total de Exames Vencido' = ```
			
			COALESCE(    
			    CALCULATE(
			        COUNTROWS(Asos),
			        Asos[VALIDADE] = "Vencido"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: d597186d-c63e-4ba6-873a-73e343135c41

	measure 'Total de Exames Pendente' = ```
			
			COALESCE(    
			    CALCULATE(
			        COUNTROWS(Asos),
			        Asos[VALIDADE] = "Pendente"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 3fe58107-6bdf-497f-ab17-129cf84907df

	partition Metricas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

