table Metricas
	lineageTag: a16a904e-f54f-42b0-b0ba-74f24013478b

	measure 'Total de Exames Em Dia' = ```
			
			CALCULATE(
			    COUNTROWS(Asos),
			    Asos[VALIDADE] = "Em Dia"
			)
			
			```
		formatString: 0
		lineageTag: 4b3b80a2-00c3-459c-8d61-f901c454af7a

	measure 'Total de Exames A Vencer (COALESCE)' = ```
			
			COALESCE(    
			    CALCULATE(
			        COUNTROWS(Asos),
			        Asos[VALIDADE] = "A Vencer"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 81c8e370-0654-4223-8c3e-d7506f9035d4

	measure 'Total de Exames Vencido' = ```
			
			CALCULATE(
			    COUNTROWS(Asos),
			    Asos[VALIDADE] = "Vencido"
			)
			
			```
		formatString: 0
		lineageTag: d597186d-c63e-4ba6-873a-73e343135c41

	measure 'Total de Exames Pendente' = ```
			
			CALCULATE(
			    COUNTROWS(Asos),
			    Asos[VALIDADE] = "Pendente"
			)
			
			```
		formatString: 0
		lineageTag: 3fe58107-6bdf-497f-ab17-129cf84907df

	measure 'Total de Exames' = COUNTROWS(Asos)
		formatString: 0
		lineageTag: 7032f2c0-2b94-4c8b-a672-2571fd1df226

	measure 'Total de Exames A Vencer' = ```
			
			CALCULATE(
			    COUNTROWS(Asos),
			    Asos[VALIDADE] = "A Vencer"
			)
			
			```
		formatString: 0
		lineageTag: 333c681f-68e8-43f1-bb8a-458912ea9cff

	measure 'Total de Exames Em Dia (COALESCE)' = ```
			
			COALESCE(    
			    CALCULATE(
			        COUNTROWS(Asos),
			        Asos[VALIDADE] = "Em Dia"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 34ef6c31-27ed-40ae-af40-70d01709ca9d

	measure 'Total de Exames Pendente (COALESCE)' = ```
			
			COALESCE(    
			    CALCULATE(
			        COUNTROWS(Asos),
			        Asos[VALIDADE] = "Pendente"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: cfa2e221-5d67-4729-b96b-7850cfb223d2

	measure 'Total de Exames Vencido (COALESCE)' = ```
			
			COALESCE(    
			    CALCULATE(
			        COUNTROWS(Asos),
			        Asos[VALIDADE] = "Vencido"
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 2bb0f769-5676-4bf3-924d-f04521123594

	measure 'Total de Exames (COALESCE)' = ```
			
			COALESCE(    
			    COUNTROWS(Asos),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 49d7bab6-0492-48e3-bd72-2b4b7d4ccee4

	partition Metricas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

