table Medidas
	lineageTag: 4adeaf7a-45d9-428a-bbb5-bc2056efc8ef

	measure FATURAMENTOLIQ = SUM(Faturamento[VALORLIQUIDO])
		lineageTag: 5c4b3f01-9632-4dd6-a406-f23a9b4e29a0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure FATURAMENTOBRT = SUM(Faturamento[VALORBRUTO])
		lineageTag: f35fe1e3-e025-49fd-a8c4-bf74e95b6f32

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Medidas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

