table Metricas
	lineageTag: b20bf460-b2d3-4a99-a0b2-cd44443f7e25

	measure TOTAL_DE_ACIDENTES = COUNTROWS(CATs)
		formatString: 0
		lineageTag: d9d6bb61-25b5-4c7a-8080-9be4f9d918cd

	measure TOTAL_DE_ACIDENTES_COM_AFASTAMENTO = ```
			
			COALESCE(
			    COUNTROWS(
			        FILTER(
			            CATs,
			            (
			                CATs[DURACAOTRATAMENTO] > 1 &&
			                CATs[MORTE] = "Não"
			            )
			        )
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 1e392217-0eaf-4e73-b12c-0cd5f17917e5

	measure TOTAL_DE_ACIDENTES_SEM_AFASTAMENTO = ```
			
			COALESCE(
			    COUNTROWS(
			        FILTER(
			            CATs,
			            (
			                CATs[DURACAOTRATAMENTO] <= 1 &&
			                CATs[MORTE] = "Não"
			            )
			        )
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: d6331908-51ea-4a35-a5fb-64fc4128a618

	measure TOTAL_DE_ACIDENTES_COM_OBITO = ```
			
			COALESCE(
			    COUNTROWS(
			        FILTER(
			            CATs,
			            (
			                CATs[MORTE] = "Sim"
			            )
			        )
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: dde00515-bd3d-40f6-80e2-4fbed481055e

	partition Metricas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

