table Metricas
	lineageTag: b20bf460-b2d3-4a99-a0b2-cd44443f7e25

	measure TOTAL_DE_ACIDENTES = COUNTROWS(CATs)
		formatString: 0
		lineageTag: d9d6bb61-25b5-4c7a-8080-9be4f9d918cd

	partition Metricas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

