WITH PERFIS AS (
		SELECT DISTINCT
				VPERFIL.CODCOLIGADA,
				VPERFIL.CODPERFIL,
				VBATERIAEXAMES.CODEXAME
				
		FROM VPERFIL
				JOIN VBATERIAEXAMES ON
						VBATERIAEXAMES.CODCOLIGADA=VPERFIL.CODCOLIGADA
					AND VBATERIAEXAMES.CODPERFIL=VPERFIL.CODPERFIL
)

SELECT 
		PFUNC.CODCOLIGADA,
		PFUNC.CHAPA,
		PFUNC.NOME,
		PSECAO.DESCRICAO AS SECAO,
		PFUNCAO.NOME AS FUNCAO,
		PCODSITUACAO.DESCRICAO AS SITUACAO,
		VEXAMESPEND.CODPERFIL,
		VEXAMESPEND.CODEXAME,
		VEXAMES.NOMEEXAME,
		VEXAMESPEND.TIPOEXAME,
		VTIPOEXAME.DESCRICAO AS NOMETIPOEXAME,
		VEXAMESPEND.DATAPROXEXAME AS DATAEXAME,
		CASE
			WHEN VEXAMESPEND.REALIZADO = 0 THEN 'Pendente'
			WHEN VEXAMESPEND.REALIZADO = 1 THEN 'Realizado'
			WHEN VEXAMESPEND.REALIZADO = 2 THEN 'Excluido'
		END AS SITUACAOEXAME

FROM PFUNC 
		JOIN PSECAO (NOLOCK) ON
				PSECAO.CODIGO=PFUNC.CODSECAO
			AND PSECAO.CODCOLIGADA=PFUNC.CODCOLIGADA
		JOIN PFUNCAO (NOLOCK) ON
				PFUNCAO.CODIGO=PFUNC.CODFUNCAO
			AND PFUNCAO.CODCOLIGADA=PFUNC.CODCOLIGADA
		JOIN PCODSITUACAO (NOLOCK) ON
				PCODSITUACAO.CODCLIENTE=PFUNC.CODSITUACAO
		FULL JOIN VEXAMESPEND (NOLOCK) ON
				PFUNC.CODCOLIGADA=VEXAMESPEND.CODCOLIGADA
			AND PFUNC.CHAPA=VEXAMESPEND.CHAPA
		LEFT JOIN VTIPOEXAME (NOLOCK) ON
				VTIPOEXAME.CODCLIENTE=VEXAMESPEND.TIPOEXAME
		JOIN VEXAMES (NOLOCK) ON
				VEXAMES.CODCOLIGADA=VEXAMESPEND.CODCOLIGADA
			AND VEXAMES.CODEXAME=VEXAMESPEND.CODEXAME

WHERE 1=1
		AND VEXAMESPEND.REALIZADO = 0
		AND PFUNC.CODSITUACAO <> 'D'

ORDER BY
		PFUNC.NOME
