WITH PERFIS AS (
		SELECT DISTINCT
				VPERFIL.CODCOLIGADA,
				VPERFIL.CODPERFIL,
				VPERFIL.NOMEPERFIL,
				VBATERIAEXAMES.CODEXAME,
				VEXAMES.NOMEEXAME
				
		FROM VPERFIL
				JOIN VBATERIAEXAMES ON
						VBATERIAEXAMES.CODCOLIGADA=VPERFIL.CODCOLIGADA
					AND VBATERIAEXAMES.CODPERFIL=VPERFIL.CODPERFIL
				JOIN VEXAMES (NOLOCK) ON
						VEXAMES.CODCOLIGADA=VBATERIAEXAMES.CODCOLIGADA
					AND VEXAMES.CODEXAME=VBATERIAEXAMES.CODEXAME
),

PERFILCOLABORADOR AS (
		SELECT
				PFUNC.CODCOLIGADA,
				PFUNC.CHAPA,
				(
						SELECT TOP 1 
								CODPERFIL 
						
						FROM VEXAMESPEND 
						
						WHERE 1=1
							AND CODCOLIGADA=PFUNC.CODCOLIGADA 
							AND CODPESSOA=PFUNC.CODPESSOA 
							AND CHAPA=PFUNC.CHAPA 
						
						ORDER BY 
								DATAPROXEXAME DESC
				) AS CODPERFIL

		FROM PFUNC 

		WHERE 1=1
				AND PFUNC.CODSITUACAO <> 'D'
)

SELECT 
		PERFILCOLABORADOR.CODCOLIGADA, 
		PERFILCOLABORADOR.CHAPA, 
		PFUNC.NOME,
		PFUNC.CODSECAO,
		PSECAO.DESCRICAO AS SECAO,
		PFUNC.CODFUNCAO,
		PFUNCAO.NOME AS FUNCAO,
		PFUNC.CODSITUACAO,
		PCODSITUACAO.DESCRICAO AS SITUACAO,
		PERFILCOLABORADOR.CODPERFIL, 
		PERFIS.NOMEPERFIL,
		PERFIS.CODEXAME,
		PERFIS.NOMEEXAME,
		(
				SELECT TOP 1 TIPOEXAME FROM VEXAMESPEND 				
				WHERE 1=1
					AND VEXAMESPEND.CODCOLIGADA=PERFILCOLABORADOR.CODCOLIGADA
					AND VEXAMESPEND.CHAPA=PERFILCOLABORADOR.CHAPA
					AND	VEXAMESPEND.CODPERFIL=PERFILCOLABORADOR.CODPERFIL
					AND	VEXAMESPEND.CODEXAME=PERFIS.CODEXAME 
					AND VEXAMESPEND.REALIZADO = 0
				ORDER BY 
						DATAPROXEXAME DESC
		) AS TIPOEXAME,
		(
				SELECT TOP 1 VTIPOEXAME.DESCRICAO FROM VEXAMESPEND
						LEFT JOIN VTIPOEXAME (NOLOCK) ON
								VTIPOEXAME.CODCLIENTE=VEXAMESPEND.TIPOEXAME
				WHERE 1=1
					AND VEXAMESPEND.CODCOLIGADA=PERFILCOLABORADOR.CODCOLIGADA
					AND VEXAMESPEND.CHAPA=PERFILCOLABORADOR.CHAPA
					AND	VEXAMESPEND.CODPERFIL=PERFILCOLABORADOR.CODPERFIL
					AND	VEXAMESPEND.CODEXAME=PERFIS.CODEXAME 
					AND VEXAMESPEND.REALIZADO = 0
				ORDER BY 
						DATAPROXEXAME DESC
		) AS NOMETIPOEXAME,
		(
				SELECT TOP 1 DATAPROXEXAME FROM VEXAMESPEND 				
				WHERE 1=1
					AND VEXAMESPEND.CODCOLIGADA=PERFILCOLABORADOR.CODCOLIGADA
					AND VEXAMESPEND.CHAPA=PERFILCOLABORADOR.CHAPA
					AND	VEXAMESPEND.CODPERFIL=PERFILCOLABORADOR.CODPERFIL
					AND	VEXAMESPEND.CODEXAME=PERFIS.CODEXAME 
					AND VEXAMESPEND.REALIZADO = 0
				ORDER BY 
						DATAPROXEXAME DESC
		) AS DATAEXAME,
		(
				SELECT TOP 1 REALIZADO FROM VEXAMESPEND 				
				WHERE 1=1
					AND VEXAMESPEND.CODCOLIGADA=PERFILCOLABORADOR.CODCOLIGADA
					AND VEXAMESPEND.CHAPA=PERFILCOLABORADOR.CHAPA
					AND	VEXAMESPEND.CODPERFIL=PERFILCOLABORADOR.CODPERFIL
					AND	VEXAMESPEND.CODEXAME=PERFIS.CODEXAME 
					AND VEXAMESPEND.REALIZADO = 0
				ORDER BY 
						DATAPROXEXAME DESC
		) AS SITUACAOEXAME

FROM PERFILCOLABORADOR 
		JOIN PERFIS ON 
				PERFIS.CODCOLIGADA=PERFILCOLABORADOR.CODCOLIGADA 
			AND PERFIS.CODPERFIL=PERFILCOLABORADOR.CODPERFIL
		JOIN PFUNC ON 
				PFUNC.CODCOLIGADA=PERFILCOLABORADOR.CODCOLIGADA 
			AND PFUNC.CHAPA=PERFILCOLABORADOR.CHAPA
		JOIN PSECAO (NOLOCK) ON
				PSECAO.CODIGO=PFUNC.CODSECAO
			AND PSECAO.CODCOLIGADA=PFUNC.CODCOLIGADA
		JOIN PFUNCAO (NOLOCK) ON
				PFUNCAO.CODIGO=PFUNC.CODFUNCAO
			AND PFUNCAO.CODCOLIGADA=PFUNC.CODCOLIGADA
		JOIN PCODSITUACAO (NOLOCK) ON
				PCODSITUACAO.CODCLIENTE=PFUNC.CODSITUACAO

ORDER BY
		PERFILCOLABORADOR.CODCOLIGADA,
		PERFILCOLABORADOR.CHAPA
