WITH PERFILS AS (
		SELECT DISTINCT
				VPERFIL.CODCOLIGADA,
				VPERFIL.CODPERFIL,
				VPERFIL.NOMEPERFIL,
				VBATERIAEXAMES.CODEXAME,
				VEXAMES.NOMEEXAME

		FROM VPERFIL
				JOIN VBATERIAEXAMES (NOLOCK) ON
						VBATERIAEXAMES.CODCOLIGADA=VPERFIL.CODCOLIGADA
					AND VBATERIAEXAMES.CODPERFIL=VPERFIL.CODPERFIL
				JOIN VEXAMES (NOLOCK) ON
						VEXAMES.CODCOLIGADA=VBATERIAEXAMES.CODCOLIGADA
					AND VEXAMES.CODEXAME=VBATERIAEXAMES.CODEXAME
),

EXAMES AS (
		SELECT 
				PFUNC.CODCOLIGADA,
				PFUNC.CHAPA,
				PFUNC.NOME,
				PSECAO.DESCRICAO AS SECAO,
				PFUNCAO.NOME AS FUNCAO,
				PCODSITUACAO.DESCRICAO AS SITUACAO,
				VEXAMESPEND.CODPERFIL,
				VEXAMESPEND.CODEXAME,
				VEXAMES.NOMEEXAME,
				VEXAMESPEND.TIPOEXAME,
				VTIPOEXAME.DESCRICAO AS NOMETIPOEXAME,
				VEXAMESPEND.DATAPROXEXAME AS DATAEXAME,
				CASE
					WHEN VEXAMESPEND.REALIZADO = 0 THEN 'Pendente'
					WHEN VEXAMESPEND.REALIZADO = 1 THEN 'Realizado'
					WHEN VEXAMESPEND.REALIZADO = 2 THEN 'Excluido'
				END AS SITUACAOEXAME
		
		FROM VEXAMESPEND
				LEFT JOIN VTIPOEXAME (NOLOCK) ON
						VTIPOEXAME.CODCLIENTE=VEXAMESPEND.TIPOEXAME
				JOIN VEXAMES (NOLOCK) ON
						VEXAMES.CODCOLIGADA=VEXAMESPEND.CODCOLIGADA
					AND VEXAMES.CODEXAME=VEXAMESPEND.CODEXAME
				FULL JOIN PFUNC (NOLOCK) ON
						PFUNC.CODCOLIGADA=VEXAMESPEND.CODCOLIGADA
					AND PFUNC.CHAPA=VEXAMESPEND.CHAPA
				JOIN PSECAO (NOLOCK) ON
						PSECAO.CODIGO=PFUNC.CODSECAO
					AND PSECAO.CODCOLIGADA=PFUNC.CODCOLIGADA
				JOIN PFUNCAO (NOLOCK) ON
						PFUNCAO.CODIGO=PFUNC.CODFUNCAO
					AND PFUNCAO.CODCOLIGADA=PFUNC.CODCOLIGADA
				JOIN PCODSITUACAO (NOLOCK) ON
						PCODSITUACAO.CODCLIENTE=PFUNC.CODSITUACAO
)

SELECT * FROM EXAMES 

WHERE 1=1
	AND EXAMES.SITUACAOEXAME = 'Pendente'
	AND EXAMES.SITUACAO <> 'Demitido'

ORDER BY
		EXAMES.NOME
