WITH COLABORADORES AS (
    SELECT
        GCOLIGADA.CODCOLIGADA,
        GCOLIGADA.NOMEFANTASIA,
        PPESSOA.CODIGO,
        PFUNC.CHAPA,
        PFUNC.NOME,
        PFUNC.DATAADMISSAO,
        PFUNCAO.NOME AS FUNCAO,
        PCODSITUACAO.DESCRICAO AS SITUACAO,
        PPESSOA.DTVENCHABILIT,
        PFCOMPL.EXAMECNH AS VENCIMENTOCNH,
        PFCOMPL.VALIDADEMOPP,

        CASE
            WHEN PFCOMPL.EAR = 'T' THEN 1
            ELSE 0
        END AS EAR
        
    FROM PFUNC
        JOIN PPESSOA ON PPESSOA.CODIGO = PFUNC.CODPESSOA
        JOIN PFCOMPL ON PFUNC.CODCOLIGADA = PFCOMPL.CODCOLIGADA AND PFUNC.CHAPA = PFCOMPL.CHAPA
        JOIN PFUNCAO ON PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA AND PFUNC.CODFUNCAO = PFUNCAO.CODIGO
        JOIN PCODSITUACAO ON PFUNC.CODSITUACAO = PCODSITUACAO.CODCLIENTE
        JOIN GCOLIGADA ON PFUNC.CODCOLIGADA = GCOLIGADA.CODCOLIGADA
    
    WHERE 
        PFUNC.CODFUNCAO IN ('02','02.01','05.05','22','73') AND PFUNC.CODSITUACAO <> 'D'
),

EXAMES AS (
    SELECT 
        ROW_NUMBER() OVER(PARTITION BY VEXAMESPRONT.CODPESSOA ORDER BY VEXAMESPRONT.DATAEXAME DESC) AS ID,
        VEXAMESPRONT.CODCOLIGADA,
        VEXAMESPRONT.CODPESSOA,
        VEXAMESPRONT.DATAEXAME
    FROM VEXAMESPRONT
    WHERE VEXAMESPRONT.CODEXAME = '0030'
)

SELECT
    COLABORADORES.CODCOLIGADA,
    COLABORADORES.NOMEFANTASIA,
    COLABORADORES.CODIGO,
    COLABORADORES.CHAPA,
    COLABORADORES.NOME,
    COLABORADORES.DATAADMISSAO,
    COLABORADORES.FUNCAO,
    COLABORADORES.SITUACAO,
    COLABORADORES.EAR,
    COLABORADORES.DTVENCHABILIT,
    COLABORADORES.VENCIMENTOCNH,
    COLABORADORES.VALIDADEMOPP,
    DATEADD(MONTH, 30, EXAMES.DATAEXAME) AS VENCIMENTO,

    CASE
        WHEN COLABORADORES.DTVENCHABILIT IS NULL OR COLABORADORES.DTVENCHABILIT < GETDATE() THEN 'Vencido'
        WHEN COLABORADORES.DTVENCHABILIT BETWEEN GETDATE() AND DATEADD(MONTH, 1, GETDATE()) THEN 'A Vencer'
        ELSE 'Em Dia'
    END AS STATUSHABILITCNH,
    
    CASE
        WHEN COLABORADORES.VENCIMENTOCNH IS NULL OR COLABORADORES.VENCIMENTOCNH < GETDATE() THEN 'Vencido'
        WHEN COLABORADORES.VENCIMENTOCNH BETWEEN GETDATE() AND DATEADD(MONTH, 2, GETDATE()) THEN 'A Vencer'
        ELSE 'Em Dia'
    END AS STATUSCNH,

    CASE
        WHEN COLABORADORES.VALIDADEMOPP IS NULL OR COLABORADORES.VALIDADEMOPP < GETDATE() THEN 'Vencido'
        WHEN COLABORADORES.VALIDADEMOPP BETWEEN GETDATE() AND DATEADD(MONTH, 2, GETDATE()) THEN 'A Vencer'
        ELSE 'Em Dia'
    END AS STATUSMOPP,

    CASE
        WHEN EXAMES.DATAEXAME IS NULL OR DATEADD(MONTH, 30, EXAMES.DATAEXAME) < GETDATE() THEN 'Vencido'
        WHEN DATEADD(MONTH, 30, EXAMES.DATAEXAME) BETWEEN GETDATE() AND DATEADD(MONTH, 2, GETDATE()) THEN 'A Vencer'
        ELSE 'Em Dia'
    END AS STATUSEMP,

    CASE
        WHEN 
            (EXAMES.DATAEXAME IS NULL OR DATEADD(MONTH, 30, EXAMES.DATAEXAME) < GETDATE()) OR
            (COLABORADORES.VENCIMENTOCNH IS NULL OR COLABORADORES.VENCIMENTOCNH < GETDATE()) OR
            (COLABORADORES.VALIDADEMOPP IS NULL OR COLABORADORES.VALIDADEMOPP < GETDATE()) OR
            (COLABORADORES.DTVENCHABILIT IS NULL OR COLABORADORES.VENCIMENTOCNH < GETDATE()) OR
            COLABORADORES.EAR <> 1
        THEN 'Pendente'
        ELSE 'Em Dia'
    END AS STATUS
        
FROM COLABORADORES
    LEFT JOIN EXAMES ON 
        EXAMES.CODCOLIGADA = COLABORADORES.CODCOLIGADA 
        AND EXAMES.CODPESSOA = COLABORADORES.CODIGO 
        AND EXAMES.ID = 1

ORDER BY NOME
