WITH TEMPTABLE AS (
    SELECT
        (SELECT COUNT(*) FROM PFUNC WHERE DATAADMISSAO BETWEEN '2025-01-01' AND '2025-12-31') AS ADMITIDOS,
        (SELECT COUNT(*) FROM PFUNC WHERE DATADEMISSAO BETWEEN '2025-01-01' AND '2025-12-31') AS DEMITIDOS,
        (SELECT COUNT(*) FROM PFUNC WHERE DATAADMISSAO <= '2025-12-31' AND (DATADEMISSAO IS NULL OR DATADEMISSAO > '2025-12-31')) AS COLABORADORES
)
SELECT
    ADMITIDOS,
    DEMITIDOS,
    COLABORADORES,
    CAST(((ADMITIDOS + DEMITIDOS) / 2.0) / COLABORADORES * 100 AS DECIMAL(10,2)) AS [TURNOVER (%)]

FROM TEMPTABLE
